# Generated by Django 6.0.6 on 2026-06-11 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=20, unique=True, verbose_name='شماره فاکتور')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='مبلغ (تومان)')),
                ('description', models.TextField(blank=True, verbose_name='شرح')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('approved', 'تایید مالی'), ('paid', 'وصول شده'), ('cancelled', 'ابطال شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('zibal_track_id', models.CharField(blank=True, max_length=100, verbose_name='کد پیگیری زیبال')),
                ('payment_url', models.URLField(blank=True, verbose_name='لینک پرداخت')),
                ('ref_number', models.CharField(blank=True, max_length=100, verbose_name='شماره مرجع بانکی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ صدور')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expert_invoices', to=settings.AUTH_USER_MODEL, verbose_name='کارشناس')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='leads.lead', verbose_name='سرنخ')),
            ],
            options={
                'verbose_name': 'فاکتور',
                'verbose_name_plural': 'فاکتورها',
                'ordering': ['-created_at'],
            },
        ),
    ]
